### ISSUE TITLE
0.4 feature tracking list

### ISSUE THREAD

**Issue by letoram** [letoram/senseye#17]
It's time to bring senseye back from hibernation now that arcan etc. has improved as much as it has. This issue just tracks what needs to be done "in the great refactoring":

- [ ] rework WM code to act more like a normal desktop program
- [x] merge sense- and xlt- support into libsenseye
- [x] add terminal support with presets in place for adding sensors/translators
- [ ] document libsenseye API
- [ ] migrate sensors and translators to use shmif-tui when rendering
- [ ] refactor the UI code base to more cleanly separate WM/UI/integration
- [ ] bring UI back to 0.3 level features
  - [ ] file sensor
  - [ ] mfile sensor
  - [ ] memory sensor
  - [ ] histo-view
  - [ ] data-view
  - [ ] picture-tuner
  - [ ] translators
  - [ ] overlays
- [ ] improve window management (minimize, expand/collapse)
- [ ] all features accessible through keybindings and UI
- [ ] saving / loading matching patterns
- [ ] dwarf- capable translator
